### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by liuxin-SH** [vvasilo/yolov3_pytorch_ros#1]
![2020-08-05 17-36-45屏幕截图](https://user-images.githubusercontent.com/56961236/89397298-45f94980-d742-11ea-8383-2f680d666f4b.png)
How to solve this mistake？
Please have a look. Thank you
![2020-08-05 17-36-45屏幕截图](https://user-images.githubusercontent.com/56961236/89397659-b3a57580-d742-11ea-9d4f-9d492afbf15e.png)

**Comment by flynneva** [comment]
the new updates just merged in should fix this issue I think. could you pull the new code and try again?
