### ISSUE TITLE
do you care if I publish this package to ros?

### ISSUE THREAD

**Issue by flynneva** [vvasilo/yolov3_pytorch_ros#3]
this package (including the re-writes I made in #2) could be really useful for others and I think publishing it for others to download as binaries for easy installation and setup.

is it OK with you if I publish it to ROS and maintain it?

**Comment by flynneva** [comment]
also, I might try and rewrite it for ROS2 if thats ok as well

**Comment by vvasilo** [comment]
Everything sounds good! I just merged your pull request - feel free to publish the package to ROS and let me know if you need anything else!

**Comment by flynneva** [comment]
@vvasilo sounds great! Would you rather me publish it from my forked repo? If you make me a collaborator on your repo here I can release it from this one.

It might be better since this is the original repo rather than a forked version.

**Comment by vvasilo** [comment]
I just added you!
